all:
    vars:
        ansible_user: root
        ansible_port: 8090
    children:
        vm_cooking_center:
            hosts:
                proxmox:
        services:
            hosts:
                rahbia-services:
                rahbia-runner:
                rahbia-voting-app: