all:
    vars:
        ansible_user: root
        ansible_port: 8090
    children:
        hypervisors:
            hosts:
                proxmox:
        services:
            hosts:
                rahbia-services:
                rahbia-runner:
                rahbia-development:
                rahbia-production:
