---
- name: Check anonymous config
  uri:
    url: "{{ NEXUS_MAIN_URL }}/service/rest/v1/security/anonymous"
    method: GET
    user: "{{ NEXUS_USERNAME }}"
    password: "{{ NEXUS_PASSWORD }}"
    force_basic_auth: yes
    status_code: 200
  register: anonymous_check_response
  tags:
    - setup_nexus
    - config_nexus
    - anonymous_config

- name: Create anonymous config
  uri:
    url: "{{ NEXUS_MAIN_URL }}/service/rest/v1/security/anonymous"
    user: "{{ NEXUS_USERNAME }}"
    password: "{{ NEXUS_PASSWORD }}"
    method: PUT
    force_basic_auth: yes
    status_code: 200
    body_format: json
    headers:
      Content-Type: "application/json"
    body: >-
      {
        "enabled": "{{ ANONYMOUS_CONFIG.enabled }}",
        "userId": "{{ ANONYMOUS_CONFIG.userId }}",
        "realmName": "{{ ANONYMOUS_CONFIG.realmName }}"
      }
  when: anonymous_check_response.json.enabled == false

  tags:
    - setup_nexus
    - config_nexus
    - anonymous_config