---
- name: Setup Nexus Service
  import_tasks: nexus_setup.yml
  tags:
    - install_nexus
    - setup_nexus

- name: Wait for URL to return 200 OK
  uri:
    url: "{{ NEXUS_MAIN_URL }}/service/rest/v1/status"
    method: GET
    status_code: 200
    timeout: 10
  register: nexus_availablity
  until: nexus_availablity.status == 200
  retries: 20
  delay: 10

- name: nexus config | anonymous config
  import_tasks: anonymous_config.yml
  tags:
    - setup_nexus
    - config_nexus
    - anonymous_config

- name: nexus config | realms config
  include_tasks: realms_config.yml
  tags:
    - setup_nexus
    - config_nexus
    - realms_config

- name: nexus config | role and user config
  include_tasks: auth_config.yml
  tags:
    - setup_nexus
    - config_nexus
    - auth_config

- name: nexus config | create blob
  include_tasks: create_blob.yml
  loop: "{{ CREATE_BLOB }}"
  loop_control:
    loop_var: item
  tags:
    - setup_nexus
    - config_nexus
    - create_blob

- name: nexus config | delete repository
  include_tasks: delete_repo.yml
  loop: "{{ DELETE_REPOSITORY }}"
  loop_control:
    loop_var: item
  tags:
    - setup_nexus
    - config_nexus
    - delete_repository

- name: nexus config | create apt repository
  include_tasks: create_apt_repo.yml
  loop: "{{ CREATE_APT_REPOSITORY }}"
  loop_control:
    loop_var: item
  tags:
    - setup_nexus
    - config_nexus
    - create_apt_repo

- name: nexus config | create docker repository
  include_tasks: create_docker_repo.yml
  loop: "{{ CREATE_DOCKER_REPOSITORY }}"
  loop_control:
    loop_var: item
  tags:
    - setup_nexus
    - config_nexus
    - create_docker_repo

- name: nexus config | create raw repository
  include_tasks: create_raw_repo.yml
  loop: "{{ CREATE_RAW_REPOSITORY }}"
  loop_control:
    loop_var: item
  tags:
    - setup_nexus
    - config_nexus
    - create_raw_repo

- name: nexus config | create pipy repository
  include_tasks: create_pypi_repo.yml
  loop: "{{ CREATE_PYPI_REPOSITORY }}"
  loop_control:
    loop_var: item
  tags:
    - setup_nexus
    - config_nexus
    - create_pypi_repo
