---

- name: Creates directory /root/.config/pip
  ansible.builtin.file:
    path: "/root/.config/pip/"
    state: directory
  tags:
    - preparing

- name: Copy pip.conf with owner and permissions
  ansible.builtin.copy:
    src: pip.conf
    dest: "/root/.config/pip/pip.conf"
  tags:
    - preparing

- name: Install multi python packages
  ansible.builtin.pip:
    name:
      - docker
      - PyYAML==5.3.1
      - docker-compose

- name: Create a docker network with name
  docker_network:
    name: "{{ item }}"
    driver_options:
      com.docker.network.bridge.name: "{{ item }}"
  loop:
    - web_net
    - app_net
  tags:
    - preparing
    - docker

- name: Creates directory {{ service_dir }}
  ansible.builtin.file:
    path: "{{ service_dir }}"
    state: directory
  tags:
    - preparing

- name: Template and Copy compose.yml.j2 to {{ service_dir }}/compose.yml
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ service_dir }}/compose.yml"
  tags:
    - preparing

- name: Template and Copy .env.j2 to {{ service_dir }}/.env
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ service_dir }}/.env"
  tags:
    - preparing

- name: Deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ service_dir }}"
    files:
      - compose.yml
    state: present
  tags:
    - setup
