---
- name: Check realms config
  uri:
    url: "{{ NEXUS_MAIN_URL }}/service/rest/v1/security/realms/active"
    user: "{{ NEXUS_USERNAME }}"
    password: "{{ NEXUS_PASSWORD }}"
    method: GET
    force_basic_auth: yes
    status_code: 200
  register: realms_check_response
  tags:
    - setup_nexus
    - config_nexus
    - realms_config

- name: Debug DockerToken if found
  debug:
    msg: "{{ realms_check_response.json }}"
  when: "'DockerToken' not in realms_check_response.json"
  tags:
    - setup_nexus
    - config_nexus
    - realms_config

- name: change realms config
  uri:
    url: "{{ NEXUS_MAIN_URL }}/service/rest/v1/security/realms/active"
    user: "{{ NEXUS_USERNAME }}"
    password: "{{ NEXUS_PASSWORD }}"
    method: PUT
    force_basic_auth: yes
    status_code: 204
    body_format: json
    headers:
      Content-Type: "application/json"
    body: >-
      [
        "NexusAuthenticatingRealm",
        "DockerToken"
      ]
  when: "'DockerToken' not in realms_check_response.json"
  tags:
    - setup_nexus
    - config_nexus
    - realms_config