---
- name: delete VMs
  hosts: all
  become: true
  gather_facts: yes
  vars_files:
    - ../../roles/proxmox/group_vars/all.yml  # Adjust the path if necessary
  roles:
    - { role: ../../roles/proxmox/delete_vm, tags: 'delete_vms' }