---
- name: Ensure SSH directories exist
  file:
    path: "{{ item.home }}/.ssh"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0700'
  loop: "{{ VM.SSH_USERS }}"

- name: Update authorized keys for users
  authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ item.authorized_keys | join('\n') }}"
    exclusive: true
  loop: "{{ VM.SSH_USERS }}"

- name: Set current date and time in ISO8601 format
  set_fact:
    current_date_time: "{{ lookup('pipe', 'date -u +%Y-%m-%dT%H:%M:%SZ') }}"

- name: Log SSH key updates
  lineinfile:
    path: /var/log/ssh_keys_updates.log
    line: "SSH keys updated for {{ item.username }} on VM {{ VM.NAME }} - {{ current_date_time }}"
    create: yes
    mode: '0640'
  loop: "{{ VM.SSH_USERS }}"