---
- name: Setup VMs
  import_tasks: create_vms.yml
  tags:
    - create_vms
    - vms_management
    - setup_vms

- name: Create ssh Config
  import_tasks: create_ssh_config.yml
  tags:
    - create_vms
    - vms_management
    - setup_vms
    - create_ssh_config

- name: Change Disk partions
  import_tasks: lvm_resize.yml
  tags:
    - create_vms
    - resize_lvm
    - vms_management
    - setup_vms